<a href="https://colab.research.google.com/github/bolpide/NEWJACK_EX/blob/main/0705ex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hellow world!!")

hellow world!!


1) mupy 샘플코드
$y=ax+b$ 


In [ ]:
import numpy as np

x = np.array([[1,2,3],[4,5,6]])
print("x:\n" , x)

x:
 [[1 2 3]
 [4 5 6]]


2) Scipy 샘플코드

In [ ]:
from scipy import sparse
#대각선 원소는 1이고 나마지는 0인 2차원 num파일 배열을 만듦
eye = np.eye(4)
print("numpy 배열:\n",eye)

numpy 배열:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
sparse_matrix = sparse.csr_matrix(eye)
print("scipy의 csr행렬: \n",sparse_matrix )

data = np.ones(4)


scipy의 csr행렬: 
   (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


In [ ]:
data = np.ones(4)
row_indices = np.arange(4)
col_indices = np.arange(4)
eye_coo = sparse.coo_matrix((data,(row_indices,col_indices)))

print("coo표현:\:n", eye_coo)

coo표현:\:n   (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


In [ ]:
import matplotlib.pyplot as plt
x= np.linspace(-10,10,100)
y = np.sin(x)
plt.plot(x.y.maker = 'x')
plt.show()

SyntaxError: ignored

4) pandas 샘플코드

In [ ]:
import pandas as pd

data = {'Name':["Jhon","Anna","Peter","Linda"],
      'Location':["N.Y","Paris","Berlin","London"],
      'Age':[24,12,35,35]
}

data_pandas = pd.DataFrame(data)

from IPython.display import display

display(data_pandas)


Name Location  Age
0   Jhon      N.Y   24
1   Anna    Paris   12
2  Peter   Berlin   35
3  Linda   London   35

In [4]:
def sum(a,b):
    return a+b
x = 10.0
y = 20.0
print("%.1f + %.1f = %.1f" %(x,y,sum(x,y))  )

10.0 + 20.0 = 30.0


※ 리스트에 관한 문법

In [5]:
a= []
b=[1,2,3]
c = ["Hello",",","world"]
d = [1,2,3,"x","y","z"]
x= []
print(x)
x.append('a')
print(x)
x.append(123)
print(x)
x.append(["a","b"])
print(x)

[]
['a']
['a', 123]
['a', 123, ['a', 'b']]


※ 딕셔너리 문법

In [8]:
dic = dict()
dic["name"] ="hyoseok"
dic["town"] = "Seoul City"
dic["job"] = "AIStudent"
print (dic)

{'name': 'hyoseok', 'town': 'Seoul City', 'job': 'AIStudent'}


※ 